baseURL = "https://bastien.jaillot.fr/dette-technique-le-livre/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Livre \"La dette technique\" par Bastien Jaillot"
#theme = "beautifulhugo"
theme = "hugo-journal"
rssLimit = 0

[taxonomies]
  tag = "tags"

[params]
  description = "Bastien Jaillot — développeur Web — co-fondateur @jolicode et @opengovfr"
  shortTitle = "La dette technique"

[Author]
  name = "Bastien Jaillot"
  website = "https://bastien.jaillot.fr"
  email = "bastien@jaillot.fr"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "bastnic"
  gitlab = "bjaillot"
  twitter = "bastnic"
  #linkedin = "username"
  paypal = "bjaillot"
  telegram = "Bastien Jaillot"
