baseURL = "https://bastien.jaillot.fr/dette-technique/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Livre \"La dette technique\" par Bastien Jaillot"
#theme = "beautifulhugo"
theme = "hugo-journal"
rssLimit = 0

[taxonomies]
  tag = "tags"

[params]
  description = "Bastien Jaillot — développeur web — co-fondateur @jolicode et @opengovfr"

[Author]
  name = "Bastien Jaillot"
  website = "https://bastien.jaillot.fr"
  email = "bastien@jaillot.fr"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "bastnic"
  gitlab = "bjaillot"
  twitter = "bastnic"
  #linkedin = "username"
  paypal = "bjaillot"
  telegram = "Bastien Jaillot"

  [[menu.main]]
      name = "Blog"
      url = ""
      weight = 1

  [[menu.main]]
      name = "About"
      url = "page/about/"
      weight = 3
